Library Framework Update
RockLib/RockLib.Diagnostics pull request #9
Opened 2022-02-22 19:14 UTC by eslutz

## Description

Updated target frameworks to net6.0, netcoreapp3.1, and net48.

Added .editorconfig and Directory.Build.props for consistency.

## Type of change: 4

1. Non-functional change (e.g. documentation changes, removing unused `using` directives, renaming local variables, etc)
2. Bug fix (non-breaking change that fixes an issue)
3. New feature (non-breaking change that adds functionality)
4. Breaking change (fix or feature that could cause existing functionality to not work as expected)
---

<sup>_[Reviewer guidelines](../blob/main/CONTRIBUTING.md#reviewing-changes)_</sup>

2022-02-22 19:23 UTC, eslutz commented on RockLib.Diagnostics/Tracing.cs
> +#pragma warning disable CA1724
[CA1724: Type names should not match namespaces](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1724) - Suggested to suppress for already existing libraries.

2022-02-22 19:27 UTC, eslutz commented on RockLib.Diagnostics.ConfigTests/Tracing/CustomTraceListener.cs
> +#pragma warning disable CA1050 // Declare types in namespaces
[CA1050: Declare types in namespaces](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1050) - It says "It is safe to suppress a warning from this rule if performance is not a concern" so I'm suppressing it after spending time unsuccessfully adding it to a namespace without causing test failures.

2022-02-22 19:30 UTC, eslutz commented on RockLib.Diagnostics.Tests/ConfigurationExtensions/CreateDiagnosticsSettingsTests.cs
> +#if !NET48
After lots of debugging and then even more debugging with @JasonBock there is an issue specifically with .NET 4.8 causing these two tests to fail, so the tests will be skipped in that case.

2022-02-23 13:31 UTC, JasonBock requested changes

2022-02-23 13:31 UTC, JasonBock commented on RockLib.Diagnostics.Tests/DebugTraceListenerTests.cs
> +            traceListener.Dispose();
`using var traceListener = new DebugTraceListener();` will call `Dispose()` for you. I'd change your code where you're calling `Dispose()` explicitly to this.

2022-02-23 13:31 UTC, JasonBock commented on RockLib.Diagnostics.Tests/Tracing/ConfigureTraceTests.cs
> +#pragma warning disable CA1810 // Initialize reference type static fields inline
I think you can set the fields inline, like:
```
private static readonly bool InitialAutoFlush = Trace.AutoFlush;
```
The `Initialize()` call still needs to be done in the type initializer.

2022-02-23 13:40 UTC, kristycurrier commented
What is the code coverage on this?

2022-02-23 14:51 UTC, eslutz commented
> What is the code coverage on this?

@kristycurrier code coverage is at 96.86%

![image](https://user-images.githubusercontent.com/67699321/155343477-a4b1a36f-a2bd-4345-b10c-d398967ff22f.png)

2022-02-23 15:22 UTC, motionsuggests approved these changes

2022-02-23 15:32 UTC, NeilSchiefer commented
I think you need to update the appveyor config(s) right?

2022-02-23 15:52 UTC, NeilSchiefer approved these changes

2022-02-23 16:02 UTC, merged